# Generated by Django 4.1.7 on 2023-03-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerWeb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="header"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Icons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=50)),
                ("icons", models.ImageField(blank=True, null=True, upload_to="icons")),
            ],
        ),
    ]
